env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  import/prefer-default-export: off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': warn
  import/extensions: off
  max-len: [warn, 140]
  '@typescript-eslint/explicit-function-return-type': off
